// AUTO-GENERATED by scripts/generate-gallery.mjs — do not edit manually.
// To regenerate: node scripts/generate-gallery.mjs
//
// To add/remove photos, just add or delete image files from the folders
// under public/images/ (pre-wedding, blessings, couple, signing, family, portraits, feast).
// Optionally update _captions.json in that folder for alt text and captions.

import { GalleryPhoto } from '@/components/PhotoGallery';

export const preWeddingGalleryPhotos: GalleryPhoto[] = [
  { src: '/images/pre-wedding/prewedding_02.jpg', alt: 'Rituparna and Shoumo in an antique room with warm amber tones and vintage furniture', caption: 'Amber light, timeless grace' },
  { src: '/images/pre-wedding/prewedding_01.jpg', alt: 'Wide view of an ornate heritage haveli corridor with arched doorways and warm light', caption: 'Where the story begins — a corridor of anticipation' },
  { src: '/images/pre-wedding/prewedding_03.jpg', alt: 'Rituparna adjusting her hair in a mirror reflection, a candid moment of preparation', caption: 'A quiet moment before the world rushes in' },
  { src: '/images/pre-wedding/prewedding_04.jpg', alt: 'Portrait of Rituparna and Shoumo framed by green-shuttered windows of the haveli', caption: 'Framed by heritage, coloured by love' },
  { src: '/images/pre-wedding/prewedding_05.jpg', alt: 'Shoumo kneeling in the haveli corridor in a chivalrous, cinematic pose', caption: 'A promise whispered in the corridor of time' },
  { src: '/images/pre-wedding/prewedding_06.jpg', alt: 'Rituparna by an exterior column, tucking her hair with a gentle gesture', caption: 'Grace in the smallest gestures' },
  { src: '/images/pre-wedding/prewedding_07.jpg', alt: 'Wide shot of Rituparna and Shoumo playfully posing before the grand haveli facade', caption: 'Playful hearts against grand walls' },
  { src: '/images/pre-wedding/prewedding_08.jpg', alt: 'Wide shot of Rituparna and Shoumo kissing before the haveli facade', caption: 'A kiss sealed in stone and sunlight' },
  { src: '/images/pre-wedding/prewedding_09.jpg', alt: 'Black and white close-up of Rituparna and Shoumo with foreheads touching tenderly', caption: 'Where words end, foreheads meet' },
  { src: '/images/pre-wedding/prewedding_10.jpg', alt: 'Dramatic window silhouette of the couple in black and white', caption: 'Light and shadow, love and longing' },
  { src: '/images/pre-wedding/prewedding_11.jpg', alt: 'Window silhouette of the couple sharing a kiss, black and white', caption: 'A silhouette worth a thousand words' },
  { src: '/images/pre-wedding/prewedding_12.jpg', alt: 'Black and white close-up of the couple with ethereal backlighting', caption: 'Ethereal — where light dissolves into love' },
  { src: '/images/pre-wedding/prewedding_13.jpg', alt: 'Wide shot of the opulent palace darbar hall with fairy lights and red drapes', caption: 'The palace awaits — fairy lights and crimson dreams' },
  { src: '/images/pre-wedding/prewedding_14.jpg', alt: 'Rituparna and Shoumo dancing and twirling joyfully in the palace hall', caption: 'Lost in the music of each other' },
  { src: '/images/pre-wedding/prewedding_15.jpg', alt: 'Rituparna and Shoumo together on the palace steps with lotus motifs', caption: 'On steps carved with stories of their own' },
  { src: '/images/pre-wedding/prewedding_16.jpg', alt: 'Detail shot of clasped hands resting on the lotus-carved palace steps', caption: 'Hands that found each other and never let go' },
  { src: '/images/pre-wedding/prewedding_17.jpg', alt: 'Rituparna and Shoumo walking through a sunlit park, laughing together', caption: 'Sunlit laughter, the simplest kind of magic' },
  { src: '/images/pre-wedding/prewedding_18.jpg', alt: 'Rituparna and Shoumo sharing a nose kiss in the park surrounded by greenery', caption: 'A stolen moment between the leaves' },
  { src: '/images/pre-wedding/prewedding_19.jpg', alt: 'Close-up of Rituparna laughing with genuine, radiant joy', caption: 'This laugh — the reason for everything' },
  { src: '/images/pre-wedding/prewedding_20.jpg', alt: 'Rituparna and Shoumo embracing beneath a canopy of palm trees', caption: 'Shelter found in each other, under a canopy of palms' },
  { src: '/images/pre-wedding/prewedding_21.jpg', alt: 'Dramatic black and white shot under an ancient tree canopy with sprawling branches', caption: 'Roots run deep — a love story as old as the trees' },
  { src: '/images/pre-wedding/prewedding_22.jpg', alt: 'Black and white cinematic shot of the couple walking down a tree-lined avenue', caption: 'Walking into forever, one frame at a time' },
  { src: '/images/pre-wedding/prewedding_23.jpg', alt: 'Black and white shot of Rituparna and Shoumo standing under a grand banyan tree', caption: 'Under the banyan — two souls, one shade' },
  { src: '/images/pre-wedding/prewedding_24.jpg', alt: 'Shoumo kissing Rituparna\'s forehead tenderly among the trees', caption: 'A forehead kiss worth a thousand promises' },
  { src: '/images/pre-wedding/prewedding_25.jpg', alt: 'Rituparna and Shoumo walking hand in hand, looking at each other and laughing', caption: 'Hand in hand, step by step — this is how forever begins' },
  { src: '/images/pre-wedding/prewedding_26.jpg', alt: 'Black and white wide shot of the couple walking through a forest clearing', caption: 'Into the woods, into each other — a love story in monochrome' },
];

export const blessingPhotos: GalleryPhoto[] = [
  { src: '/images/blessings/ashirwad_001.jpg', alt: 'Rituparna seated on the ceremonial carpet receiving ashirwad from an elder', caption: 'শুভ আশীর্বাদ — where it all begins, on the carpet of tradition' },
  { src: '/images/blessings/ashirwad_002.jpg', alt: 'KumKum Ma lovingly feeding Shoumo sweets during the ceremony', caption: 'মিষ্টিমুখ — KumKum Ma feeds Shoumo mishti, sweetness to start the journey' },
  { src: '/images/blessings/ashirwad_007.jpg', alt: 'Family members seated together on the decorative prayer mat during ashirwad', caption: 'On the prayer mat, surrounded by love — the ashirwad begins' },
  { src: '/images/blessings/ashirwad_009.jpg', alt: 'Elder man in white blessing Rituparna in her purple Banarasi', caption: 'হাতের আশীর্বাদ — a hand on her head, a prayer in the heart' },
  { src: '/images/blessings/ashirwad_013.jpg', alt: 'Elder man embracing and blessing Shoumo in his red kurta', caption: 'An elder\'s embrace — blessings flow through every touch' },
  { src: '/images/blessings/ashirwad_021.jpg', alt: 'Grandfather in white blessing Rituparna seated on the prayer mat', caption: 'ঠাকুরদার আশীর্বাদ — a grandfather\'s blessing, worth a thousand words' },
  { src: '/images/blessings/ashirwad_025.jpg', alt: 'Woman in orange sari helping a child with ceremonial activity on the mat', caption: 'The youngest learns the oldest traditions — blessings passed down' },
  { src: '/images/blessings/ashirwad_031.jpg', alt: 'Woman in teal sari with Rituparna on the prayer mat during ashirwad', caption: 'Kaki whispers a lifetime of love into a single touch' },
  { src: '/images/blessings/ashirwad_040.jpg', alt: 'Blessing ritual on the carpet with sacred items and family gathered', caption: 'প্রদীপের আলোয় আশীর্বাদ — blessings by the light of the sacred flame' },
  { src: '/images/blessings/ashirwad_049.jpg', alt: 'Man in maroon receiving blessings from an elder woman in green', caption: 'On this carpet, every blessing becomes a promise' },
  { src: '/images/blessings/ashirwad_050.jpg', alt: 'Woman in green sari blessing Rituparna in purple on the prayer mat', caption: 'In green and in grace — love pours from her hands' },
  { src: '/images/blessings/ashirwad_055.jpg', alt: 'Woman in gold sari blessing Rituparna seated on the prayer mat', caption: 'প্রণাম — Rituparna bows, and a lifetime of respect flows' },
  { src: '/images/blessings/ashirwad_060.jpg', alt: 'Woman in green blessing Rituparna during the ceremony', caption: 'Shoumo bows, humble before the love of his elders' },
  { src: '/images/blessings/ashirwad_061.jpg', alt: 'Elderly woman blessing Shoumo in an intimate close moment', caption: 'মায়ের আশীর্বাদ — a mother\'s blessing that carries lifetimes of love' },
  { src: '/images/blessings/ashirwad_072.jpg', alt: 'Man in green bending to receive blessings with family watching', caption: 'সাষ্টাঙ্গ প্রণাম — the deepest bow, the highest respect' },
  { src: '/images/blessings/ashirwad_074.jpg', alt: 'Man kneeling as woman in gold offers blessings, Rituparna seated nearby', caption: 'Sweets from the brass thali — every morsel a prayer' },
  { src: '/images/blessings/ashirwad_079.jpg', alt: 'Man in maroon kurta blessing Rituparna with woman in green as witness', caption: 'Dada blesses Rituparna — welcoming her into the family with open arms' },
  { src: '/images/blessings/ashirwad_081.jpg', alt: 'Elderly man in maroon kurta blessing Rituparna seated on the mat', caption: 'Two hands, one prayer — ashirwad from the eldest' },
  { src: '/images/blessings/ashirwad_096.jpg', alt: 'Elder man in maroon kurta and younger man in black standing together during the celebration', caption: 'প্রজন্ম থেকে প্রজন্ম — standing tall together, across generations' },
  { src: '/images/blessings/ashirwad_087.jpg', alt: 'Woman in white clothing bending to bless Rituparna on the prayer mat', caption: 'প্রণাম — touching feet, touching hearts' },
  { src: '/images/blessings/ashirwad_091.jpg', alt: 'Elder in white giving blessings to Shoumo on the prayer mat', caption: 'আশীর্বাদের ধারা — the stream of blessings continues unbroken' },
  { src: '/images/blessings/ashirwad_093.jpg', alt: 'Man in white receiving blessings from woman and Shoumo during ceremony', caption: 'KumKum Ma blesses her daughter — eyes full of pride, heart full of love' },
  { src: '/images/blessings/ashirwad_100.jpg', alt: 'Man in white kurta blessing Rituparna on the prayer mat', caption: 'দীপ আর দূর্বা — the eternal symbols of Bengali blessings' },
  { src: '/images/blessings/ashirwad_104.jpg', alt: 'Elder woman and man performing blessings with Shoumo on the prayer mat', caption: 'Fed with love, blessed with grace — the Bengali way' },
  { src: '/images/blessings/ashirwad_109.jpg', alt: 'Elderly woman in turquoise sari blessing Rituparna on the prayer mat', caption: 'মায়ের আদর — Shoumo\'s Ma opens her arms to Rituparna' },
  { src: '/images/blessings/ashirwad_112.jpg', alt: 'Shoumo\'s family exchanging blessings with gifts and brass items', caption: 'রক্ষাসূত্র — the sacred thread that binds blessings to the wrist' },
  { src: '/images/blessings/ashirwad_129.jpg', alt: 'Woman giving blessings to Shoumo seated on the prayer mat', caption: 'Meson Mama\'s blessings — loud in love, gentle in touch' },
  { src: '/images/blessings/ashirwad_138.jpg', alt: 'Elder woman in turquoise tenderly blessing Rituparna on the floor', caption: 'She blesses Rituparna the way only a grandmother can — with her whole soul' },
  { src: '/images/blessings/ashirwad_147.jpg', alt: 'Shoumo and Rituparna in a playful moment as someone records on phone', caption: 'Peace, love, and a little mischief — that\'s them!' },
  { src: '/images/blessings/ashirwad_180.jpg', alt: 'Elder man in maroon blessing Shoumo on the decorative mat', caption: 'From the hands of elders, every morsel is a memory' },
  { src: '/images/blessings/ashirwad_249.jpg', alt: 'Rituparna and Shoumo reviewing documents together on the couch', caption: 'A quiet pause in the celebration — every moment matters' },
  { src: '/images/blessings/ashirwad_207.jpg', alt: 'Elder woman and man performing blessing ritual with Shoumo kneeling', caption: 'A gentle touch, a world of wishes' },
  { src: '/images/blessings/ashirwad_226.jpg', alt: 'Elder man in white blessing Rituparna seated on the prayer mat', caption: 'Blessings in every gesture — bold, warm, and unforgettable' },
  { src: '/images/blessings/ashirwad_230.jpg', alt: 'Elder man bending to bless Rituparna with family standing nearby', caption: 'The women of the family — the pillars of every blessing' },
  { src: '/images/blessings/ashirwad_254.jpg', alt: 'Elder man placing hand on Rituparna\'s head in blessing on the prayer mat', caption: 'মাথায় হাত — a hand on her head, a lifetime of protection' },
  { src: '/images/blessings/ashirwad_014.jpg', alt: 'Rituparna bowing at an elder woman\'s feet on the prayer mat during ashirwad', caption: 'প্রণাম — the deepest respect, offered at her feet' },
  { src: '/images/blessings/ashirwad_122.jpg', alt: 'Rituparna smiling warmly in her purple Banarasi seated on the prayer mat', caption: 'রিতুপর্ণা — a smile that lights up the whole room' },
];

export const couplePhotos: GalleryPhoto[] = [
  { src: '/images/couple/ashirwad_078.jpg', alt: 'Rituparna and Shoumo wearing flower garlands, smiling together near a window', caption: 'যুগলবন্দী — a portrait of two souls in perfect harmony' },
  { src: '/images/couple/ashirwad_044.jpg', alt: 'Rituparna and Shoumo standing together after exchanging garlands', caption: 'মালাবদল — the garlands exchanged, two hearts now one' },
  { src: '/images/couple/ashirwad_062.jpg', alt: 'Rituparna and Shoumo laughing together with garlands by the staircase', caption: 'By the staircase — standing tall, hearts intertwined' },
  { src: '/images/couple/ashirwad_076.jpg', alt: 'Rituparna in purple Banarasi and Shoumo in red kurta wearing matching garlands', caption: 'Garlanded and glowing — this is what love looks like' },
  { src: '/images/couple/ashirwad_083.jpg', alt: 'Rituparna and Shoumo in a formal portrait together in their wedding attire', caption: 'A portrait for the ages — purple meets red, grace meets warmth' },
  { src: '/images/couple/ashirwad_089.jpg', alt: 'Rituparna\'s radiant smile captured candidly at the celebration', caption: 'That smile could light up all of Kolkata' },
  { src: '/images/couple/ashirwad_098.jpg', alt: 'Shoumo smiling in his red kurta, surrounded by family at the celebration', caption: 'শৌমো — handsome, happy, and ready for forever' },
  { src: '/images/couple/ashirwad_102.jpg', alt: 'Rituparna and Shoumo exchanging flower garlands with an elder woman assisting', caption: 'মালা বদল — the moment two souls make their promise visible' },
  { src: '/images/couple/ashirwad_111.jpg', alt: 'Rituparna and Shoumo standing together with garlands, beaming with joy', caption: 'সিঁড়ির ধারে — every step together, every step closer' },
  { src: '/images/couple/ashirwad_117.jpg', alt: 'Rituparna in purple Banarasi and Shoumo in red kurta, portrait together indoors', caption: 'A portrait by the stairs — timeless and beautiful' },
  { src: '/images/couple/ashirwad_122.jpg', alt: 'Rituparna in her purple Banarasi smiling at the camera during the ceremony', caption: 'রিতুপর্ণা — radiance that needs no filter' },
  { src: '/images/couple/ashirwad_134.jpg', alt: 'Rituparna and Shoumo seated together wearing garlands, joyful moment', caption: 'Seated in bliss, wrapped in garlands and গল্প' },
  { src: '/images/couple/ashirwad_142.jpg', alt: 'Rituparna and Shoumo with matching flower garlands, smiling directly at camera', caption: 'Close enough to see forever in each other\'s eyes' },
  { src: '/images/couple/ashirwad_145.jpg', alt: 'Rituparna tenderly touching Shoumo\'s forehead, both wearing garlands', caption: 'The gentlest blessing — from one heart to another' },
  { src: '/images/couple/ashirwad_148.jpg', alt: 'Rituparna and Shoumo smiling happily together at the celebration venue', caption: 'That smile after মালা বদল — pure, unfiltered joy' },
  { src: '/images/couple/ashirwad_151.jpg', alt: 'Close-up of Rituparna and Shoumo smiling, bride in purple and groom in red', caption: 'Two people, one heartbeat — দুটি প্রাণ, একটি ধড়কানি' },
  { src: '/images/couple/ashirwad_169.jpg', alt: 'Rituparna and Shoumo holding flower garlands together, smiling indoors', caption: 'Peace signs and garlands — because love should always be this fun' },
  { src: '/images/couple/ashirwad_202.jpg', alt: 'Rituparna and Shoumo seated together wearing garlands, smiling at camera', caption: 'Surrounded by love and লোকজন — the warmest company' },
  { src: '/images/couple/ashirwad_247.jpg', alt: 'Rituparna in her purple Banarasi with flower decorations in her hair, portrait', caption: 'রিতুপর্ণা — stunning, graceful, and absolutely herself' },
];

export const signingPhotos: GalleryPhoto[] = [
  { src: '/images/signing/ashirwad_085.jpg', alt: 'Man in white kurta placing arm on Rituparna\'s head in blessing', caption: 'Garlands and blessings, woven together like destiny' },
  { src: '/images/signing/ashirwad_005.jpg', alt: 'Rituparna and Shoumo reviewing documents together on the couch', caption: 'Reading their future together — one page at a time' },
  { src: '/images/signing/ashirwad_011.jpg', alt: 'The couple in a quiet moment over paperwork between rituals', caption: 'Between all the rituals, a quiet moment just for them' },
  { src: '/images/signing/ashirwad_022.jpg', alt: 'Woman in red sari reviewing and signing ceremony documents', caption: 'Babai signs — steady hand, proud heart' },
  { src: '/images/signing/ashirwad_030.jpg', alt: 'Elder and Shoumo reviewing papers together on the blue couch', caption: 'An elder\'s signature — wisdom sealed in ink' },
  { src: '/images/signing/ashirwad_033.jpg', alt: 'Rituparna in purple and Shoumo in red signing documents on the couch', caption: 'The paperwork of promise — making forever official' },
  { src: '/images/signing/ashirwad_064.jpg', alt: 'Overhead shot of two people reviewing ceremony documents on the floor', caption: 'মা-র স্বাক্ষর — Ma signs with love in every stroke' },
  { src: '/images/signing/ashirwad_077.jpg', alt: 'Elder man bending over to sign papers alongside Shoumo in red kurta', caption: 'Another witness, another blessing on paper' },
  { src: '/images/signing/ashirwad_099.jpg', alt: 'Woman in red sari carefully signing the ceremony documents', caption: 'KumKum Ma signs — a mother\'s seal of love and approval' },
  { src: '/images/signing/ashirwad_103.jpg', alt: 'Elder man in white with Shoumo, reviewing documents during the ceremony', caption: 'The ceremony pauses for formalities — every signature a blessing' },
  { src: '/images/signing/ashirwad_107.jpg', alt: 'Rituparna and Shoumo signing documents together during the ceremony', caption: 'Pen in hand, future in heart — কলমে ভবিষ্যৎ' },
  { src: '/images/signing/ashirwad_114.jpg', alt: 'Overhead shot of Rituparna and Shoumo signing documents on the bed', caption: 'দুটি স্বাক্ষর, একটি প্রতিশ্রুতি — two signatures, one promise' },
  { src: '/images/signing/ashirwad_116.jpg', alt: 'Elder man in white and Shoumo signing marriage documents on the floor', caption: 'সাক্ষী হলেন বড়রা — elders witnessed, promises were sealed' },
  { src: '/images/signing/ashirwad_127.jpg', alt: 'Rituparna and Shoumo casually signing documents on the couch', caption: 'Signing the next chapter — ink and intentions' },
  { src: '/images/signing/ashirwad_155.jpg', alt: 'Rituparna and Shoumo reviewing documents together on the blue couch', caption: 'Under the canopy of celebrations' },
  { src: '/images/signing/ashirwad_160.jpg', alt: 'Elder man in white reviewing ceremony papers with Shoumo', caption: 'Reading every word — because promises deserve attention' },
  { src: '/images/signing/ashirwad_086.jpg', alt: 'Rituparna and Shoumo smiling at each other, wearing garlands', caption: 'That look — when the whole world fades and only you remain' },
  { src: '/images/signing/ashirwad_132.jpg', alt: 'Rituparna and Shoumo at the dining table with other guests', caption: 'বিরিয়ানি আর হাসি — biryani and laughter, the Bengali combo' },
  { src: '/images/signing/ashirwad_135.jpg', alt: 'Rituparna and Shoumo at the dining table during the wedding feast', caption: 'জলখাবারের টেবিল — refreshments that say "you are loved"' },
  { src: '/images/signing/ashirwad_166.jpg', alt: 'Elder woman in red and gold sari giving blessing with ceremonial items', caption: 'ঠাকুমার আশীর্বাদ — when grandmother blesses, even the heavens listen' },
  { src: '/images/signing/ashirwad_194.jpg', alt: 'Shoumo placing a flower garland on Rituparna\'s head as she smiles', caption: 'ফুলের মালা, ভালোবাসার মালা — garlanded with love' },
  { src: '/images/signing/ashirwad_260.jpg', alt: 'Elder woman in orange blessing Shoumo with a hand gesture', caption: 'Another garland, another prayer answered' },
];

export const familyPhotos: GalleryPhoto[] = [
  { src: '/images/family/ashirwad_000.jpg', alt: 'Family group photo with Babai, Ma, KumKum Ma, Rituparna, and Shoumo by the staircase', caption: 'দুটি পরিবার, একটি হৃদয় — two families, one heart, one frame' },
  { src: '/images/family/ashirwad_003.jpg', alt: 'Didi Monalisa and Manish together during the ceremony', caption: 'Didi Monalisa and Manish — love from the sister\'s side' },
  { src: '/images/family/ashirwad_008.jpg', alt: 'Extended family group photo in traditional attire', caption: 'The whole family — loud, loving, and perfectly Bengali' },
  { src: '/images/family/ashirwad_035.jpg', alt: 'Two women standing elegantly in beautiful green and pink saris', caption: 'শাড়িতে সাজানো — dressed in tradition, draped in elegance' },
  { src: '/images/family/ashirwad_052.jpg', alt: 'Two women in purple and green saris smiling at the camera', caption: 'মায়েদের আড্ডা — the women of the family, the heart of every celebration' },
  { src: '/images/family/ashirwad_054.jpg', alt: 'Six family members in formal wedding attire posing together', caption: 'Smiles and saris — the real festive spirit' },
  { src: '/images/family/ashirwad_059.jpg', alt: 'Six family members in wedding clothes standing together at home', caption: 'The staircase portrait — every generation represented' },
  { src: '/images/family/ashirwad_067.jpg', alt: 'Multi-generational group of six seated together during the gathering', caption: 'তিন প্রজন্ম — three generations, one frame, endless love' },
  { src: '/images/family/ashirwad_073.jpg', alt: 'Man and woman in traditional cream attire posing together at home', caption: 'Outside the বাড়ি — where every wall holds a memory' },
  { src: '/images/family/ashirwad_095.jpg', alt: 'Group portrait at home with Shoumo and multiple relatives in traditional attire', caption: 'Stairs make the best stages for family portraits' },
  { src: '/images/family/ashirwad_105.jpg', alt: 'Woman in green and purple sari standing elegantly at the venue entrance', caption: 'সাজানো বাড়ি — the house dressed up for the occasion' },
  { src: '/images/family/ashirwad_125.jpg', alt: 'White and grey cat lying regally on the floor', caption: 'বিড়ালও এসেছে আশীর্বাদ দিতে — even the cat showed up to bless the couple!' },
  { src: '/images/family/ashirwad_141.jpg', alt: 'Wide-angle view of the large family gathered in the ceremony room', caption: 'The ceremony buzzes — every corner alive with celebration' },
  { src: '/images/family/ashirwad_262.jpg', alt: 'Father and son together in a warm selfie moment', caption: 'বাবা আর ছেলে — a father\'s pride, captured in a click' },
  { src: '/images/family/ashirwad_267.jpg', alt: 'Couple with child and family members at the doorway in traditional attire', caption: 'Shoumo with Dada, Dadu, Dida & Ma — his roots, his strength' },
  { src: '/images/family/ashirwad_269.jpg', alt: 'Mixed group of men and women seated together indoors during the ceremony', caption: 'মায়ের অভ্যর্থনা — a mother\'s welcome at the threshold of forever' },
  { src: '/images/family/ashirwad_270.jpg', alt: 'Elder man and younger man in traditional white attire', caption: 'All together — a family that fits anywhere' },
];

export const portraitSectionPhotos: GalleryPhoto[] = [
  { src: '/images/portraits/rituparna_001.jpg', alt: 'Rituparna smiling at the camera in her purple Banarasi with a pink flower in her hair', caption: '' },
  { src: '/images/portraits/rituparna_002.jpg', alt: 'Rituparna looking down gracefully in her purple Banarasi with gold jewelry', caption: '' },
  { src: '/images/portraits/rituparna_003.jpg', alt: 'Rituparna smiling softly with eyes downcast, pink flower and gold necklace', caption: '' },
  { src: '/images/portraits/rituparna_004.jpg', alt: 'Rituparna in a candid moment, gentle smile in her purple Banarasi', caption: '' },
];

export const feastPhotos: GalleryPhoto[] = [
  { src: '/images/feast/ashirwad_018.jpg', alt: 'Family members gathered under a yellow tent eating together', caption: 'পরিবারের সাথে খাওয়া — nothing beats a meal with family' },
  { src: '/images/feast/ashirwad_080.jpg', alt: 'Family eating together on the terrace during the celebration', caption: 'ছাদে খাওয়া-দাওয়া — terrace meals are the best meals' },
];

// Legacy exports for backward compatibility
export const ceremonyPhotos = blessingPhotos;
export const receptionPhotos = couplePhotos;
export const portraitPhotos = familyPhotos;
export const preWeddingPhotos = feastPhotos;
